service: air-fares

provider:
  name: aws
  runtime: nodejs20.x
  profile: personal
  region: eu-west-1

functions:
  handleRequest:
    handler: handler.handleRequest
    events:
      - httpApi:
          path: /
          method: post
